export const FETCH_INITIAL = 'NOTES/FETCH_INITIAL';
export const CREATE_NOTE = 'NOTES/CREATE_NOTE';
export const DELETE_NOTE = 'NOTES/DELETE_NOTE';
export const OPEN_NOTE = 'NOTES/OPEN_NOTE';
export const SAVE_NOTE = 'NOTES/SAVE_NOTE';
export const CREATE_MOCK = 'NOTES/CREATE_MOCK';
export const UPDATE_TITLE = 'NOTES/UPDATE_TITLE';
export const UPDATE_TEXT = 'NOTES/UPDATE_TEXT';

export const RESET_FILTER = 'FILTER/RESET_FILTER';
export const CREATE_FILTER = 'FILTER/CREATE_FILTER';
export const REMOVE_FILTER = 'FILTER/REMOVE_FILTER';

export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';
